---
title: "R Notebook"
output: html_notebook
---

```{r}
## Set directory and load file to data frame
library('ggplot2')
library('tidyverse')
library('readxl')
library('plotly')
library(geojsonio)
theme_set(theme_minimal())
setwd("C:/Users/Supraja/Desktop/Supraja WORK Apps/8. DSC640/Data")

## Load data to data frame
df <- read_csv("education.csv")
```

```{r}
math <- df$math
hist(math,
     main="Math Scores by Number of States",
     xlab="Math Score",
     xlim=c(450, 650),
     ylim=c(0, 25),
     col="blue",
     breaks=c(450, 475, 500, 525, 550, 575, 600, 625, 650)
)
```
```{r}
boxplot(math, data=df, main='US Math Scores', ylab='Test Score')
```
```{r}
fig <- plot_ly(
  type = "indicator",
  mode = "number+gauge",
  value = mean(df$math),
  domain = list(x = c(0, 1), y= c(0, 1)),
  title = list(text = "Math"),
  gauge = list(
    shape = "bullet",
    axis = list(range = list(425, 625)),
    threshold = list(
      line = list(color = "red", width = 2),
      thickness = 0.75,
      value = 550),
    steps = list(
      list(range = c(425, 525), color = "lightgray"),
      list(range = c(525, 600), color = "gray"))),
  height = 150, width = 600)
fig <- fig %>%
  layout(margin = list(l= 100, r= 10))

fig
```
```{r}
fig <- plot_ly(
  domain = list(x = c(0, 1), y = c(0, 1)),
  value = mean(df$math),
  title = list(text = "US Math Scores"),
  type = "indicator",
  mode = "gauge+number")

fig <- fig %>%
  layout(margin = list(l=20,r=30))

fig
```
